-- DB-01: users-Tabelle (Postgres-Syntax seit DB-05 / ADR-12)
-- monthly_income als DECIMAL(10,2) — niemals FLOAT/REAL (ADR-9).
-- GENERATED BY DEFAULT AS IDENTITY statt AUTOINCREMENT: der SQL-Standard-Ersatz und das,
-- was GenerationType.IDENTITY in der User-Entity erwartet. BY DEFAULT (statt ALWAYS), damit
-- ein explizit gesetzter Wert — etwa aus einem Test-Fixture — nicht abgewiesen wird.
CREATE TABLE users (
    id                   BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                TEXT          NOT NULL UNIQUE,
    password_hash        TEXT          NOT NULL,
    monthly_income       DECIMAL(10,2),
    onboarding_completed BOOLEAN       NOT NULL DEFAULT FALSE
);
