-- DB-02: transactions-Tabelle (Postgres-Syntax seit DB-05 / ADR-12)
-- betrag als DECIMAL(10,2) — niemals FLOAT/REAL (ADR-9).
-- pdf_sha256 erlaubt NULL; category bleibt NULL bis zur Kategorisierung (US-05).
-- TEXT statt VARCHAR ohne Länge: in Postgres identisch im Verhalten, aber ohne die
-- Erwartung einer Längenangabe. Buchungstexte aus Bank-PDFs sind unbegrenzt lang.
CREATE TABLE transactions (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT        NOT NULL,
    buchungsdatum DATE          NOT NULL,
    buchungstext  TEXT          NOT NULL,
    betrag        DECIMAL(10,2) NOT NULL,
    is_income     BOOLEAN       NOT NULL DEFAULT FALSE,
    category      TEXT,
    pdf_sha256    TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
