-- DB-03: fixed_costs-Tabelle (Postgres-Syntax seit DB-05 / ADR-12)
-- betrag als DECIMAL(10,2) — niemals FLOAT/REAL (ADR-9).
-- intervall: Zahlungsintervall der Fixkosten-Position (z. B. monatlich, jaehrlich).
CREATE TABLE fixed_costs (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT        NOT NULL,
    bezeichnung TEXT          NOT NULL,
    betrag      DECIMAL(10,2) NOT NULL,
    intervall   TEXT          NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
