-- BE-PDF-09 / ADR-14: import_jobs-Tabelle für den asynchronen Kategorisierungslauf.
--
-- Der PDF-Upload parst synchron (~2s) und übergibt die Kategorisierung (~28s bei einem
-- 108-Zeilen-Auszug) an einen Hintergrund-Job. Diese Tabelle ist der Kanal, über den das
-- Frontend den Fortschritt abfragt: POST /api/import/pdf gibt die Job-ID zurück,
-- GET /api/import/{jobId}/status liest processed/total daraus.
--
-- Bewusst OHNE die geparsten Transaktionen: Die liegen bis zum Abschluss im Speicher des
-- Workers und werden am Ende in einem Zug nach transactions geschrieben. Sie hier
-- zwischenzulagern wäre eine zweite Wahrheit über dieselben Daten, ohne dass der Nutzer
-- vor dem Abschluss etwas davon hätte.
CREATE TABLE import_jobs (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL,
    -- Hash des importierten PDFs. Er liegt zwar auch an jeder Zeile in transactions, dort aber
    -- erst NACH dem Abschluss des Jobs — der Duplikatcheck beim Upload wäre sonst für die
    -- gesamte Dauer des Hintergrundlaufs blind (bis zu categorization-timeout plus ein
    -- Bündel). Ein zweiter Upload derselben Datei während des Laufs käme durch, und der Auszug
    -- läge doppelt in der Datenbank, ohne dass der Nutzer je bestätigt hätte. Vor ADR-14 gab es
    -- dieses Fenster nicht: Der synchrone Flow schrieb im selben Request.
    pdf_sha256    TEXT        NOT NULL,
    -- RUNNING | DONE | FAILED — als TEXT statt als Enum-Typ: eine neue Ausprägung ist damit
    -- eine Code-Änderung und keine Migration.
    status        TEXT        NOT NULL,
    -- Nenner und Zähler der Fortschrittsanzeige. total steht ab dem Anlegen fest (das Parsen
    -- ist da bereits durch), processed wächst pro abgeschlossenem Kategorisierungs-Bündel.
    total         INTEGER     NOT NULL,
    processed     INTEGER     NOT NULL DEFAULT 0,
    -- true, wenn der Watchdog zugeschlagen hat und der Rest ohne Claude-Call auf 'Sonstiges'
    -- gefallen ist. Der Import ist dann trotzdem vollständig gespeichert (AC2 aus #192).
    degraded      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at   TIMESTAMPTZ,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Jede Statusabfrage filtert auf den Job UND seinen Besitzer (Mandantentrennung, siehe
-- ImportJobRepository.findByIdAndUserId).
CREATE INDEX idx_import_jobs_user_id ON import_jobs(user_id);

-- Deckt den Duplikatcheck beim Upload ab: findByUserIdAndPdfSha256AndStatus. Der Check läuft
-- bei jedem Upload und damit auf dem Pfad, der ohnehin schon 30s Zeitbudget hat.
CREATE INDEX idx_import_jobs_user_hash_status ON import_jobs(user_id, pdf_sha256, status);

-- nDSG-Hinweis für US-02 (Konto löschen): Diese Tabelle ist ab jetzt eine weitere abhängige
-- Tabelle am User. Die Kontolöschung muss import_jobs mitlöschen — ohne das scheitert sie am
-- Fremdschlüssel. Bewusst KEIN "ON DELETE CASCADE": Die Löschung soll eine bewusste, testbare
-- Operation im Code sein (CLAUDE.md, Security-Review-Punkt 8), keine stille Nebenwirkung.
