-- DB-08: notifications-Tabelle — Datengrundlage für ein generisches In-App-Benachrichtigungs-
-- system (#245). Vorlauf-Task für US-08 ("Neu"-Label + Benachrichtigung bei erkanntem Abo);
-- NotificationService + REST-Endpoints folgen in BE-NOTIF-01.
CREATE TABLE notifications (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT        NOT NULL,
    -- Grenzt künftige Quellen ab (z. B. RECURRING_EXPENSE_DETECTED, MONTHLY_REPORT_READY).
    -- TEXT statt DB-Enum: eine neue Ausprägung ist damit eine Code-Änderung, keine Migration.
    type          TEXT          NOT NULL,
    -- Polymorpher Verweis auf die auslösende Zeile (z. B. recurring_expenses.id). Kein FK, da
    -- die Zieltabelle vom type-Wert abhängt und mit künftigen Quellen wächst.
    reference_id  BIGINT,
    message       TEXT          NOT NULL,
    -- NULL = ungelesen, gesetzter Zeitstempel = gelesen. Deckt POST /notifications/{id}/read
    -- (BE-NOTIF-01) ab, ohne ein zusätzliches Boolean-Feld.
    read_at       TIMESTAMPTZ,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Deckt den geplanten GET /api/notifications (ungelesen zuerst, pro Nutzer) aus BE-NOTIF-01 ab.
CREATE INDEX idx_notifications_user_read ON notifications(user_id, read_at);

-- nDSG-Hinweis für US-02 (Konto löschen): notifications ist ab jetzt eine weitere abhängige
-- Tabelle am User. Bewusst KEIN "ON DELETE CASCADE" (siehe DB-07/#142) — die Löschung bleibt
-- eine bewusste, testbare Operation im Code, keine stille Nebenwirkung.
