-- DB-09: recurring_expenses-Tabelle — Datengrundlage für die Abo-Erkennung (US-08, #252).
-- Zweiter Vorlauf-Task nach DB-08, dessen notifications.reference_id bereits hierher verweist.
-- Erkennung (RecurringExpenseService, BE-REC-01) und Endpoints (BE-REC-02) folgen getrennt.
--
-- V11 und nicht V09 wie im Issue-Titel: V09 (BE-AUTH-11) und V10 (DB-08) sind auf main vergeben.
-- Der Task-ID DB-09 bezeichnet das Issue, nicht die Flyway-Version.
--
-- Persistiert statt zur Laufzeit gerechnet, weil "Kein Abo" laut US-08 dauerhaft wirken muss —
-- eine reine Ableitung aus den Transaktionen könnte den Ausschluss nicht behalten.
--
-- Postgres-Syntax seit DB-05 / ADR-12. Spaltennamen englisch wie in V10; die älteren Tabellen
-- tragen "betrag" — die Inkonsistenz ist vorbestehend, AC 2 nennt "amount" ausdrücklich.
CREATE TABLE recurring_expenses (
    id                   BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT        NOT NULL,
    -- Normalisierter Empfänger: ausschliesslich in Grossschreibung gespeichert, verglichen über
    -- upper() auf beiden Seiten — dieselbe Lösung wie category_lookup (V04) und aus demselben
    -- Grund: Postgres kennt das COLLATE NOCASE der SQLite-Zeit nicht, und eine DB-Extension
    -- dafür wollte DB-05 nicht einführen. Durchsetzen wird das der Service (BE-REC-01), so wie
    -- CategoryLearningService es für V04 tut; erzwingen kann das Schema es ohne Extension nicht.
    -- TEXT statt VARCHAR(n): in Postgres verhaltensgleich, aber ohne die Erwartung einer
    -- Längenangabe — Empfängernamen aus Bank-PDFs sind unbegrenzt lang (Begründung aus V02).
    payee_key            TEXT          NOT NULL,
    -- DECIMAL(10,2) — niemals FLOAT/REAL (ADR-9).
    amount               DECIMAL(10,2) NOT NULL,
    -- Geschlossene Wertemenge, deshalb mit CHECK — anders als notifications.type (V10), das laut
    -- eigenem Kommentar mit künftigen Quellen wachsen soll und bewusst offen bleibt. Ohne die
    -- Constraint wäre ein Tippfehler im Service eine stille Datenmutation: eine Zeile, die weder
    -- in der Abo-Übersicht auftaucht noch als ausgeschlossen gilt. Ein dritter Status ist damit
    -- eine Migration — für eine Zustandsmaschine die richtige Hürde.
    -- Kein Postgres-ENUM: CREATE TYPE kommt im Projekt nirgends vor und macht jede Erweiterung
    -- zu einem ALTER TYPE.
    status               TEXT          NOT NULL
        CHECK (status IN ('DETECTED', 'DISMISSED')),
    -- Monat der ersten Erkennung, Format YYYY-MM. TEXT und nicht DATE, weil der Wert ein Monat
    -- ist und kein Datum: DATE erzwänge die Konvention "immer der 1.", die nichts durchsetzt und
    -- die jede Abfrage kennen müsste. Das Projekt spricht ohnehin durchgängig YYYY-MM
    -- (MonthParser, alle Month-Endpoints); TransactionRepository.findDistinctExpenseMonths
    -- formatiert dafür sogar mit to_char(..., 'YYYY-MM') zurück. Der lexikografische Vergleich
    -- ist für dieses Format korrekt.
    -- Bewusst ohne CHECK, obwohl status eine hat: Das Format ist eine Eingabevalidierung, und die
    -- sitzt in diesem Projekt an der Systemgrenze (MonthParser, InvalidMonthException).
    first_detected_month TEXT          NOT NULL,
    created_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    FOREIGN KEY (user_id) REFERENCES users(id),
    -- Ein Eintrag pro Empfänger und Nutzer. Das ist die strukturelle Absicherung für das
    -- dauerhafte "Kein Abo" aus US-08: BE-REC-02 setzt dafür status = 'DISMISSED', und ohne
    -- Eindeutigkeit könnte BE-REC-01 beim nächsten Import still eine zweite DETECTED-Zeile
    -- daneben schreiben — der Ausschluss wäre umgangen, ohne dass es auffiele.
    -- Die Constraint legt zugleich den Index an, den beide Endpoints brauchen: ihr
    -- user_id-Präfix bedient auch das GET /api/recurring-expenses aus BE-REC-02. Ein
    -- zusätzlicher Index auf user_id allein wäre reine Schreiblast.
    UNIQUE (user_id, payee_key)
);

-- nDSG-Hinweis für US-02 (Konto löschen): recurring_expenses ist ab jetzt eine weitere abhängige
-- Tabelle am User. Bewusst KEIN "ON DELETE CASCADE" (siehe DB-07/#142) — die Löschung bleibt eine
-- bewusste, testbare Operation im Code, keine stille Nebenwirkung. UserService.deleteUser kennt
-- diese Tabelle noch nicht; die Verpflichtung ist als AC an BE-REC-01 (#253) verankert, wo die
-- Entity entsteht, die einen RecurringExpenseCleanupPort erst möglich macht.
