-- BE-CAT-12: user_category_lookup — mandantengebundener Lerneffekt der Hybrid-Kategorisierung
-- (ADR-15, ergänzt ADR-6 Schritt 4).
--
-- Bis hierhin landete alles Gelernte — manuelle Korrekturen (BE-CAT-04) und seit BE-CAT-11 jeder
-- von Claude eingestufte Händlertext — als roher Buchungstext in category_lookup (V04), einer
-- Tabelle ohne user_id. Der Text eines Nutzers wirkte damit auf die Kategorisierung aller und
-- überlebte die Kontolöschung (#319). Ab jetzt schreibt der Lerneffekt ausschliesslich hierher,
-- pro Nutzer; category_lookup bleibt die globale, kuratierte Basis (Seeds).
--
-- Die vor dieser Migration gelernten Zeilen in category_lookup lassen sich keinem Nutzer mehr
-- zuordnen. Sie bleiben auf Teamentscheid als globale Patterns stehen (ADR-15, «Altdaten») —
-- diese Migration räumt category_lookup bewusst nicht.
--
-- Postgres-Syntax seit DB-05 / ADR-12.
CREATE TABLE user_category_lookup (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL,
    -- Ausschliesslich in Grossschreibung gespeichert, gematcht über upper() auf beiden Seiten —
    -- derselbe Vertrag wie category_lookup (V04) und recurring_expenses.payee_key (V11):
    -- Postgres kennt das COLLATE NOCASE der SQLite-Zeit nicht. Durchgesetzt vom
    -- CategoryLearningService, erzwingen kann das Schema es ohne Extension nicht.
    empfaenger_pattern TEXT   NOT NULL,
    -- Ausschliesslich Werte aus der fixen Kategorienliste (Category-Enum, siehe CLAUDE.md).
    category           TEXT   NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    -- Trägt den Upsert (INSERT … ON CONFLICT) im Repository: pro Nutzer und Pattern genau eine
    -- Zeile, die jüngste Zuordnung gewinnt — dieselbe Semantik, die category_lookup über seinen
    -- Primärschlüssel hatte.
    UNIQUE (user_id, empfaenger_pattern)
);

-- nDSG-Hinweis für US-02 (Konto löschen): user_category_lookup ist eine weitere abhängige
-- Tabelle am User. Bewusst KEIN "ON DELETE CASCADE" (siehe DB-07/#142) — die Löschung läuft
-- sichtbar über CategoryLookupCleanupPort in UserService.deleteUser und ist dort getestet.
